# Comment out the probes you don't need
# CAREFUL: yaml is super sensitive to spaces - don't use tabs
# saccfiles: ['/users/boryanah/repos/WeePeeZee/data/COADDED/power_spectra_wdpj.sacc']
saccfiles: ['/users/boryanah/repos/WeePeeZee/data/NEWCOV_COADDED/power_spectra_wdpj.sacc']

cl_params:
    fitHOD: 1
    modHOD: zevol
    fitNoise: 0
    corrHM: 1
    fstar: 1.04
#    pzMethod: COSMOS30
    bg:
        b_bin0: 1.
        b_bin1: 1.
        b_bin2: 1.
        b_bin3: 1.

sacc_params:
    cullCross: 0
    joinSaccs: 1
    singleBin: 0
    lmin: kmax
    lmax: kmax
    kmax: 1.

# Parameters to be fitted in MCMC
# [mapping_index, mean, min, max, std]
fit_params:
    zshift_bin0: [0, 0.0, -0.2, 0.2, 0.01]
    zshift_bin1: [1, 0.0, -0.2, 0.2, 0.01]
    zshift_bin2: [2, 0.0, -0.2, 0.2, 0.01]
    zshift_bin3: [3, 0.0, -0.2, 0.2, 0.01]
    lmminp:       [4, 4., -5., 10., 0.5]
    lmmin:        [5, 10., 0., 15., 0.5]
    m0p:          [6, 4., -5., 10., 0.5]
    m0:           [7, 10., 0., 15., 0.5]
    m1p:          [8, 7., -5., 10., 0.5]
    m1:           [9, 10., 0., 15., 0.5]
    zwidth_bin0: [10, 0.0, -0.2, 0.2, 0.01]
    zwidth_bin1: [11, 0.0, -0.2, 0.2, 0.01]
    zwidth_bin2: [12, 0.0, -0.2, 0.2, 0.01]
    zwidth_bin3: [13, 0.0, -0.2, 0.2, 0.01]

default_params:
    has_rsd: False
    has_magnification: null
    Omega_b: 0.0493
    Omega_k: 0.0
    sigma8: 0.8111
    h: 0.6736
    n_s: 0.9649
    Omega_c: 0.264
    #transfer_function: boltzmann_camb
    transfer_function: boltzmann_class
    matter_power_spectrum: halofit
    sigm_0: 0.4
    sigm_1: 0.
    alpha_0: 1.0
    alpha_1: 0.
    fc_0: 1.
    fc_1: 0.
    zfid: 0.65

# Configuration parameters for cosmohammer
ch_config_params:
    path2output: /users/boryanah/desclss_chains/fiducial_april12
    chainsPrefix: fiducial_april12
    use_mpi: 1
    rerun: 0
    walkersRatio: 6
    burninIterations: 2000
    sampleIterations: 10000
